### ISSUE TITLE
  InternetOpenUrl error

### ISSUE THREAD

**Issue by joshualiuxu** [adamlilith/enmSdm#102]
Hello, R found error that cannot download data from ucdavis website.

_worldClim <- getData('worldclim', var='bio', res=5)
试开URL’https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_5m_bil.zip'
Error in utils::download.file(url = aurl, destfile = fn, method = "auto",  : 
  无法打开URL'https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_5m_bil.zip'
此外: Warning message:
In utils::download.file(url = aurl, destfile = fn, method = "auto",  :
  InternetOpenUrl失败:’不能连接到吊销服务器，或者未能获得最终响应。'_

**Comment by adamlilith** [comment]
This is an error from the getData() function which is part of the raster package. I noticed the server stopped serving data last week, so it seems the problem hasn't been resolved.  In the future I will put the data into the package so this doesn't happen, but I can't fix problems with others' packages other than to remove dependencies.

**Comment by joshualiuxu** [comment]
thank you very much!

Sent from YoMail
