### ISSUE TITLE
enmSdm::trainMaxNet

### ISSUE THREAD

**Issue by Gavish-Yoni** [adamlilith/enmSdm#11]
Hi,
I'm using the package to tune maxnet:maxent as part of an  analysis of 236 pan-eurpean tree species. 
It's working really well, and it saved me considerable time writing a similar (but probably less efficient) code myself. Thanks for that!

Only a small and minor issue to report: 
the 'Out' argument in the enmSdm::trainMaxNet function does not accept 'tuning' as a meaningful value. In the code, to return the table, 'Out' should be set to 'table'.  It would be nice to change this in the help file.
Best regards,
Yoni Gavish,  
School of Geography, University of Leeds.

**Comment by adamlilith** [comment]
Hi Yoni,Thank you for letting me know--I just updated the function so it should use "tuning" now.  You can get the latest version using:install.packages('devtools') # if you haven't done this already
library(devtools)
install_github('adamlilith/omniBus')
install_github('adamlilith/omniPlots')
install_github('adamlilith/enmSdm')
# you may also need to install the "sp", "dismo", "raster", and other
# packages (all from CRAN), depending on the functions you wish to use

library(omniBus)
library(omniPlots)
library(enmSdm)By the way, I have had troubles using maxnet() (and thus trainMaxNet()).  It often gives me a Fortran error.  I believe this is in the code that the glmnet package uses, which in turn is used by the maxnet package.  I wanted to let you know in case you ran into the problem--or had a solution!Best,Adam


-------- Original Message --------
Subject: [adamlilith/enmSdm] enmSdm::trainMaxNet (#11)

**Comment by Gavish-Yoni** [comment]
Hi Adam, 
Thanks for sorting this, and in general for making this package available!

I've moved from ENMeval, Dismo and maxent.jar due to memory issues - even on the HPC (24 cores, 124 GB per node) with no parallel processing the java reached memory limits and failed.

I haven't got any Fortran related error so far, but I'm still coding and debugging a small subset of the data.  I really hope it would work fine on the full dataset with no memory related or other errors.

I'll let you know either way once it starts running on the cluster.
Best, 
Yoni

**Comment by adamlilith** [comment]
Hi Yoni,I wish you the best on your project!Best,Adam


-------- Original Message --------
Subject: Re: [adamlilith/enmSdm] enmSdm::trainMaxNet (#11)
