### ISSUE TITLE
geofold renamed to pointGoeFold, but namespace not updated

### ISSUE THREAD

**Issue by stranda** [adamlilith/enmSdm#143]
I was trying to install holoSimCell which depends on enmSdm and I'm getting an error: 
Error: package or namespace load failed for ‘enmSdm’ in namespaceExport(ns, exports):
 undefined exports: geoFold

After looking at the code, I'm pretty sure that all that needs to happen is to run devtools::document() to update the NAMESPACE file

**Comment by adamlilith** [comment]
Sorry, A! Please try the new package enmSdmX (on CRAN), which is the new version of enmSdm.

-Adam

Adam B. Smith, Ph.D.
Associate Scientist in Global Change
Center for Conservation and Sustainable Development
Missouri Botanical Garden
Saint Louis, Missouri USA
www.earthSkySea.org

________________________________
From: stranda ***@***.***>
Sent: Tuesday, December 27, 2022 1:44:49 PM
To: adamlilith/enmSdm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adamlilith/enmSdm] geofold renamed to pointGoeFold, but namespace not updated (Issue #143)


I was trying to install holoSimCell which depends on enmSdm and I'm getting an error:
Error: package or namespace load failed for ‘enmSdm’ in namespaceExport(ns, exports):
undefined exports: geoFold

After looking at the code, I'm pretty sure that all that needs to happen is to run devtools::document() to update the NAMESPACE file

**Comment by stranda** [comment]
Thanks!

**Comment by adamlilith** [comment]
FYI, I updated the NAMESPACE, so all should work now. Thanks for the catch!
Adam

**Comment by stranda** [comment]
Thanks again, but sounds like enmSdmX is a drop-in replacement, right?
cheers
a
