### ISSUE TITLE
geoThin fails when no points to discard and verbose=TRUE

### ISSUE THREAD

**Issue by ptitle** [adamlilith/enmSdm#59]
If the input dataset contains no points that are closer than minDist, then the progress bar initiated with verbose=TRUE fails, causing the function to fail.

**Comment by adamlilith** [comment]
Thanks!  This should be fixed now with version 0.3.9.7 of the enmSdm package.  A test is included in the examples to ensure geoThin doesn't crash when no sites need removed and verbose = TRUE.
